DROP TABLE IF EXISTS TB_HEROIS;
CREATE TABLE TB_HEROIS(
	ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
	NOME TEXT NOT NULL,
	PODER TEXT NOT NULL
);

--create

INSERT INTO TB_HEROIS (NOME, PODER) VALUES ('Flahs', 'Velocidade'), ('Aquaman', 'Falar com os animais'), ('Batman', 'Dinheiro')

--read
SELECT * FROM TB_HEROIS;
SELECT * FROM TB_HEROIS WHERE NOME='Flahs'

--update
UPDATE TB_HEROIS SET NOME='GOKU', PODER='deus' WHERE ID=1;

--delete
DELETE FROM TB_HEROIS WHERE ID=2